### ISSUE TITLE
Unable to install org-mode-parser

### ISSUE THREAD

**Issue by fbob** [whacked/tiddlywiki-org#1]
I've just discovered your project and it's exactly what I'm looking for. 
Thank you very much for developing it :)

Unfortunately I'm stuck at the org-mode-parser installation.
I follow the instructions but got the following errors with the `npm install` :

```
$ npm install org-mode-parser                                                                       
npm WARN install Refusing to install org-mode-parser as a dependency of itself
```

**Comment by whacked** [comment]
Hi, the latest push should obviate the need to install `org-mode-parser` and will directly pull the latest code from github by default.

You should be able to install the tiddler with `python compileorg.py -save $PATH`

**Comment by fbob** [comment]
Great, thank you very much for your kind answer.
`l14` of `compileorg.py` parentheses are missing for the `print` function call
Thank you :)

**Comment by whacked** [comment]
fixed. thanks! let me know or reopen if it still doesn't work

**Comment by fbob** [comment]
It works great, many many thanks !

For Ubuntu users, when installing `tiddlywiki` on `node.js`, please create a symbolic link between `nodejs` and `node`. `tiddlywiki` won't work otherwise, at least it was the case for me with Ubuntu 15.04.

Long life to tiddlywiki-org :)
